repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        exclude: '\.stl$|\.step$|\.f3d$|\.fzz$'
      - id: end-of-file-fixer
        exclude: '\.stl$|\.step$|\.f3d$|\.fzz$'
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=1000']
        exclude: '\.stl$|\.step$|\.f3d$|\.fzz$'
      - id: check-merge-conflict

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.0
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
      - id: mypy
        additional_dependencies: []
        args: [--ignore-missing-imports]
